#include <shuffler/Random.h>
#include <shuffler/Pokemon.h>
#include <shuffler/Database.h>
#include <emerald/include/constants/species.h>
#include <emerald/include/constants/moves.h>
#include <emerald/include/constants/items.h>

#define ARRAY_SIZE(n)   (sizeof((n)) / sizeof((n)[0]))
#define SAMPLE(rng, x)  (sample((rng), (x), ARRAY_SIZE((x))))

template <typename T>
static T sample(Random& rng, const T* array, std::size_t size)
{
    std::size_t index;

    index = randInt(rng, size);
    return array[index];
}

static const std::uint16_t kItems[] = {
    /* Balls */
    ITEM_POKE_BALL,
    ITEM_GREAT_BALL,
    ITEM_ULTRA_BALL,
    ITEM_MASTER_BALL,
    ITEM_PREMIER_BALL,
    ITEM_HEAL_BALL,
    ITEM_NET_BALL,
    ITEM_NEST_BALL,
    ITEM_DIVE_BALL,
    ITEM_DUSK_BALL,
    ITEM_TIMER_BALL,
    ITEM_QUICK_BALL,
    ITEM_REPEAT_BALL,
    ITEM_LUXURY_BALL,
    ITEM_LEVEL_BALL,
    ITEM_LURE_BALL,
    ITEM_MOON_BALL,
    ITEM_FRIEND_BALL,
    ITEM_LOVE_BALL,
    ITEM_FAST_BALL,
    ITEM_HEAVY_BALL,
    ITEM_BEAST_BALL,

    /* Heal */
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_MAX_POTION,
    ITEM_FULL_RESTORE,
    ITEM_REVIVE,
    ITEM_MAX_REVIVE,
    ITEM_FRESH_WATER,
    ITEM_SODA_POP,
    ITEM_LEMONADE,
    ITEM_MOOMOO_MILK,
    ITEM_ENERGY_POWDER,
    ITEM_ENERGY_ROOT,
    ITEM_HEAL_POWDER,
    ITEM_REVIVAL_HERB,
    ITEM_ANTIDOTE,
    ITEM_PARALYZE_HEAL,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_FULL_HEAL,
    ITEM_ETHER,
    ITEM_MAX_ETHER,
    ITEM_ELIXIR,
    ITEM_MAX_ELIXIR,
    ITEM_BERRY_JUICE,
    ITEM_SACRED_ASH,
    ITEM_SWEET_HEART,
    ITEM_MAX_HONEY,

    /* Regional */
    ITEM_PEWTER_CRUNCHIES,
    ITEM_RAGE_CANDY_BAR,
    ITEM_LAVA_COOKIE,
    ITEM_OLD_GATEAU,
    ITEM_CASTELIACONE,
    ITEM_LUMIOSE_GALETTE,
    ITEM_SHALOUR_SABLE,
    ITEM_BIG_MALASADA,

    /* Vitamins */
    ITEM_HP_UP,
    ITEM_PROTEIN,
    ITEM_IRON,
    ITEM_CALCIUM,
    ITEM_ZINC,
    ITEM_CARBOS,
    ITEM_PP_UP,
    ITEM_PP_MAX,

    /* Feathers */
    ITEM_HEALTH_FEATHER,
    ITEM_MUSCLE_FEATHER,
    ITEM_RESIST_FEATHER,
    ITEM_GENIUS_FEATHER,
    ITEM_CLEVER_FEATHER,
    ITEM_SWIFT_FEATHER,

    /* Ability items */
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,

    /* Mints */
    ITEM_LONELY_MINT,
    ITEM_ADAMANT_MINT,
    ITEM_NAUGHTY_MINT,
    ITEM_BRAVE_MINT,
    ITEM_BOLD_MINT,
    ITEM_IMPISH_MINT,
    ITEM_LAX_MINT,
    ITEM_RELAXED_MINT,
    ITEM_MODEST_MINT,
    ITEM_MILD_MINT,
    ITEM_RASH_MINT,
    ITEM_QUIET_MINT,
    ITEM_CALM_MINT,
    ITEM_GENTLE_MINT,
    ITEM_CAREFUL_MINT,
    ITEM_SASSY_MINT,
    ITEM_TIMID_MINT,
    ITEM_HASTY_MINT,
    ITEM_JOLLY_MINT,
    ITEM_NAIVE_MINT,
    ITEM_SERIOUS_MINT,

    /* Candies */
    ITEM_RARE_CANDY,
    ITEM_EXP_CANDY_XS,
    ITEM_EXP_CANDY_S,
    ITEM_EXP_CANDY_M,
    ITEM_EXP_CANDY_L,
    ITEM_EXP_CANDY_XL,

    /* Flutes */
    ITEM_BLUE_FLUTE,
    ITEM_YELLOW_FLUTE,
    ITEM_RED_FLUTE,
    ITEM_BLACK_FLUTE,
    ITEM_WHITE_FLUTE,

    /* Repels & rope */
    ITEM_REPEL,
    ITEM_SUPER_REPEL,
    ITEM_MAX_REPEL,
    ITEM_LURE,
    ITEM_SUPER_LURE,
    ITEM_MAX_LURE,
    ITEM_ESCAPE_ROPE,

    /* X-items */
    ITEM_X_ATTACK,
    ITEM_X_DEFENSE,
    ITEM_X_SP_ATK,
    ITEM_X_SP_DEF,
    ITEM_X_SPEED,
    ITEM_X_ACCURACY,
    ITEM_DIRE_HIT,
    ITEM_GUARD_SPEC,

    /* Escape */
    ITEM_POKE_DOLL,
    ITEM_FLUFFY_TAIL,
    ITEM_POKE_TOY,

    /* Evo */
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_ICE_STONE,
    ITEM_SUN_STONE,
    ITEM_MOON_STONE,
    ITEM_SHINY_STONE,
    ITEM_DUSK_STONE,
    ITEM_DAWN_STONE,
    ITEM_SWEET_APPLE,
    ITEM_TART_APPLE,
    ITEM_CRACKED_POT,
    ITEM_CHIPPED_POT,
    ITEM_GALARICA_CUFF,
    ITEM_GALARICA_WREATH,
    ITEM_DRAGON_SCALE,
    ITEM_UPGRADE,
    ITEM_PROTECTOR,
    ITEM_ELECTIRIZER,
    ITEM_MAGMARIZER,
    ITEM_DUBIOUS_DISC,
    ITEM_REAPER_CLOTH,
    ITEM_PRISM_SCALE,
    ITEM_WHIPPED_DREAM,
    ITEM_SACHET,
    ITEM_OVAL_STONE,
    ITEM_STRAWBERRY_SWEET,
    ITEM_LOVE_SWEET,
    ITEM_BERRY_SWEET,
    ITEM_CLOVER_SWEET,
    ITEM_FLOWER_SWEET,
    ITEM_STAR_SWEET,
    ITEM_RIBBON_SWEET,
    ITEM_EVERSTONE,

    /* Nectars */
    ITEM_RED_NECTAR,
    ITEM_YELLOW_NECTAR,
    ITEM_PINK_NECTAR,
    ITEM_PURPLE_NECTAR,

    /* Plates */
    ITEM_FLAME_PLATE,
    ITEM_SPLASH_PLATE,
    ITEM_ZAP_PLATE,
    ITEM_MEADOW_PLATE,
    ITEM_ICICLE_PLATE,
    ITEM_FIST_PLATE,
    ITEM_TOXIC_PLATE,
    ITEM_EARTH_PLATE,
    ITEM_SKY_PLATE,
    ITEM_MIND_PLATE,
    ITEM_INSECT_PLATE,
    ITEM_STONE_PLATE,
    ITEM_SPOOKY_PLATE,
    ITEM_DRACO_PLATE,
    ITEM_DREAD_PLATE,
    ITEM_IRON_PLATE,
    ITEM_PIXIE_PLATE,

    /* Mega Stones */
    ITEM_VENUSAURITE,
    ITEM_CHARIZARDITE_X,
    ITEM_CHARIZARDITE_Y,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_MEWTWONITE_X,
    ITEM_MEWTWONITE_Y,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LATIASITE,
    ITEM_LATIOSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_AUDINITE,
    ITEM_DIANCITE,

    /* Z-Crystals */
    ITEM_NORMALIUM_Z,
    ITEM_FIRIUM_Z,
    ITEM_WATERIUM_Z,
    ITEM_ELECTRIUM_Z,
    ITEM_GRASSIUM_Z,
    ITEM_ICIUM_Z,
    ITEM_FIGHTINIUM_Z,
    ITEM_POISONIUM_Z,
    ITEM_GROUNDIUM_Z,
    ITEM_FLYINIUM_Z,
    ITEM_PSYCHIUM_Z,
    ITEM_BUGINIUM_Z,
    ITEM_ROCKIUM_Z,
    ITEM_GHOSTIUM_Z,
    ITEM_DRAGONIUM_Z,
    ITEM_DARKINIUM_Z,
    ITEM_STEELIUM_Z,
    ITEM_FAIRIUM_Z,
    ITEM_PIKANIUM_Z,
    ITEM_EEVIUM_Z,
    ITEM_SNORLIUM_Z,
    ITEM_MEWNIUM_Z,
    ITEM_DECIDIUM_Z,
    ITEM_INCINIUM_Z,
    ITEM_PRIMARIUM_Z,
    ITEM_LYCANIUM_Z,
    ITEM_MIMIKIUM_Z,
    ITEM_KOMMONIUM_Z,
    ITEM_TAPUNIUM_Z,
    ITEM_SOLGANIUM_Z,
    ITEM_LUNALIUM_Z,
    ITEM_MARSHADIUM_Z,
    ITEM_ALORAICHIUM_Z,
    ITEM_PIKASHUNIUM_Z,
    ITEM_ULTRANECROZIUM_Z,

    /* Specific */
    ITEM_DEEP_SEA_SCALE,
    ITEM_DEEP_SEA_TOOTH,

    /* Incenses */
    ITEM_SEA_INCENSE,
    ITEM_LAX_INCENSE,
    ITEM_ODD_INCENSE,
    ITEM_ROCK_INCENSE,
    ITEM_FULL_INCENSE,
    ITEM_WAVE_INCENSE,
    ITEM_ROSE_INCENSE,
    ITEM_LUCK_INCENSE,
    ITEM_PURE_INCENSE,

    /* Type items */
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_METAL_COAT,

    /* Competitive items */
    ITEM_CHOICE_BAND,
    ITEM_CHOICE_SPECS,
    ITEM_CHOICE_SCARF,
    ITEM_FLAME_ORB,
    ITEM_TOXIC_ORB,
    ITEM_DAMP_ROCK,
    ITEM_HEAT_ROCK,
    ITEM_SMOOTH_ROCK,
    ITEM_ICY_ROCK,
    ITEM_ELECTRIC_SEED,
    ITEM_PSYCHIC_SEED,
    ITEM_MISTY_SEED,
    ITEM_GRASSY_SEED,
    ITEM_ABSORB_BULB,
    ITEM_CELL_BATTERY,
    ITEM_LUMINOUS_MOSS,
    ITEM_SNOWBALL,
    ITEM_BRIGHT_POWDER,
    ITEM_WHITE_HERB,
    ITEM_QUICK_CLAW,
    ITEM_SOOTHE_BELL,
    ITEM_MENTAL_HERB,
    ITEM_KINGS_ROCK,
    ITEM_AMULET_COIN,
    ITEM_CLEANSE_TAG,
    ITEM_SMOKE_BALL,
    ITEM_FOCUS_BAND,
    ITEM_LUCKY_EGG,
    ITEM_SCOPE_LENS,
    ITEM_LEFTOVERS,
    ITEM_SHELL_BELL,
    ITEM_WIDE_LENS,
    ITEM_MUSCLE_BAND,
    ITEM_WISE_GLASSES,
    ITEM_EXPERT_BELT,
    ITEM_LIGHT_CLAY,
    ITEM_LIFE_ORB,
    ITEM_POWER_HERB,
    ITEM_FOCUS_SASH,
    ITEM_ZOOM_LENS,
    ITEM_METRONOME,
    ITEM_IRON_BALL,
    ITEM_LAGGING_TAIL,
    ITEM_DESTINY_KNOT,
    ITEM_BLACK_SLUDGE,
    ITEM_GRIP_CLAW,
    ITEM_STICKY_BARB,
    ITEM_SHED_SHELL,
    ITEM_BIG_ROOT,
    ITEM_RAZOR_CLAW,
    ITEM_RAZOR_FANG,
    ITEM_EVIOLITE,
    ITEM_FLOAT_STONE,
    ITEM_ROCKY_HELMET,
    ITEM_AIR_BALLOON,
    ITEM_RED_CARD,
    ITEM_RING_TARGET,
    ITEM_BINDING_BAND,
    ITEM_EJECT_BUTTON,
    ITEM_WEAKNESS_POLICY,
    ITEM_ASSAULT_VEST,
    ITEM_SAFETY_GOGGLES,
    ITEM_ADRENALINE_ORB,
    ITEM_TERRAIN_EXTENDER,
    ITEM_PROTECTIVE_PADS,
    ITEM_THROAT_SPRAY,
    ITEM_EJECT_PACK,
    ITEM_HEAVY_DUTY_BOOTS,
    ITEM_BLUNDER_POLICY,
    ITEM_ROOM_SERVICE,
    ITEM_UTILITY_UMBRELLA,

    /* Berries */
    ITEM_CHERI_BERRY,
    ITEM_CHESTO_BERRY,
    ITEM_PECHA_BERRY,
    ITEM_RAWST_BERRY,
    ITEM_ASPEAR_BERRY,
    ITEM_LEPPA_BERRY,
    ITEM_ORAN_BERRY,
    ITEM_PERSIM_BERRY,
    ITEM_LUM_BERRY,
    ITEM_SITRUS_BERRY,
    ITEM_FIGY_BERRY,
    ITEM_WIKI_BERRY,
    ITEM_MAGO_BERRY,
    ITEM_AGUAV_BERRY,
    ITEM_IAPAPA_BERRY,
    ITEM_RAZZ_BERRY,
    ITEM_BLUK_BERRY,
    ITEM_NANAB_BERRY,
    ITEM_WEPEAR_BERRY,
    ITEM_PINAP_BERRY,
    ITEM_POMEG_BERRY,
    ITEM_KELPSY_BERRY,
    ITEM_QUALOT_BERRY,
    ITEM_HONDEW_BERRY,
    ITEM_GREPA_BERRY,
    ITEM_TAMATO_BERRY,
    ITEM_CORNN_BERRY,
    ITEM_MAGOST_BERRY,
    ITEM_RABUTA_BERRY,
    ITEM_NOMEL_BERRY,
    ITEM_SPELON_BERRY,
    ITEM_PAMTRE_BERRY,
    ITEM_WATMEL_BERRY,
    ITEM_DURIN_BERRY,
    ITEM_BELUE_BERRY,
    ITEM_CHILAN_BERRY,
    ITEM_OCCA_BERRY,
    ITEM_PASSHO_BERRY,
    ITEM_WACAN_BERRY,
    ITEM_RINDO_BERRY,
    ITEM_YACHE_BERRY,
    ITEM_CHOPLE_BERRY,
    ITEM_KEBIA_BERRY,
    ITEM_SHUCA_BERRY,
    ITEM_COBA_BERRY,
    ITEM_PAYAPA_BERRY,
    ITEM_TANGA_BERRY,
    ITEM_CHARTI_BERRY,
    ITEM_KASIB_BERRY,
    ITEM_HABAN_BERRY,
    ITEM_COLBUR_BERRY,
    ITEM_BABIRI_BERRY,
    ITEM_ROSELI_BERRY,
    ITEM_LIECHI_BERRY,
    ITEM_GANLON_BERRY,
    ITEM_SALAC_BERRY,
    ITEM_PETAYA_BERRY,
    ITEM_APICOT_BERRY,
    ITEM_LANSAT_BERRY,
    ITEM_STARF_BERRY,
    ITEM_ENIGMA_BERRY,
    ITEM_MICLE_BERRY,
    ITEM_CUSTAP_BERRY,
    ITEM_JABOCA_BERRY,
    ITEM_ROWAP_BERRY,
    ITEM_KEE_BERRY,
    ITEM_MARANGA_BERRY,
};

static const std::uint16_t kFormsTaurosPaldea[] = {
    SPECIES_TAUROS_PALDEA_COMBAT,
    SPECIES_TAUROS_PALDEA_BLAZE,
    SPECIES_TAUROS_PALDEA_AQUA,
};

static const uint16_t kFormsUnown[] = {
    SPECIES_UNOWN_A,
    SPECIES_UNOWN_B,
    SPECIES_UNOWN_C,
    SPECIES_UNOWN_D,
    SPECIES_UNOWN_E,
    SPECIES_UNOWN_F,
    SPECIES_UNOWN_G,
    SPECIES_UNOWN_H,
    SPECIES_UNOWN_I,
    SPECIES_UNOWN_J,
    SPECIES_UNOWN_K,
    SPECIES_UNOWN_L,
    SPECIES_UNOWN_M,
    SPECIES_UNOWN_N,
    SPECIES_UNOWN_O,
    SPECIES_UNOWN_P,
    SPECIES_UNOWN_Q,
    SPECIES_UNOWN_R,
    SPECIES_UNOWN_S,
    SPECIES_UNOWN_T,
    SPECIES_UNOWN_U,
    SPECIES_UNOWN_V,
    SPECIES_UNOWN_W,
    SPECIES_UNOWN_X,
    SPECIES_UNOWN_Y,
    SPECIES_UNOWN_Z,
    SPECIES_UNOWN_EXCLAMATION,
    SPECIES_UNOWN_QUESTION,
};

static const uint16_t kFormsDeoxys[] = {
    SPECIES_DEOXYS_NORMAL,
    SPECIES_DEOXYS_ATTACK,
    SPECIES_DEOXYS_DEFENSE,
    SPECIES_DEOXYS_SPEED,
};

static const uint16_t kFormsBurmy[] = {
    SPECIES_BURMY_PLANT,
    SPECIES_BURMY_SANDY,
    SPECIES_BURMY_TRASH,
};

static const uint16_t kFormsWormadam[] = {
    SPECIES_WORMADAM_PLANT,
    SPECIES_WORMADAM_SANDY,
    SPECIES_WORMADAM_TRASH,
};

static const uint16_t kFormsShellos[] = {
    SPECIES_SHELLOS_WEST,
    SPECIES_SHELLOS_EAST,
};

static const uint16_t kFormsGastrodon[] = {
    SPECIES_GASTRODON_WEST,
    SPECIES_GASTRODON_EAST,
};

static const uint16_t kFormsRotom[] = {
    SPECIES_ROTOM,
    SPECIES_ROTOM_HEAT,
    SPECIES_ROTOM_WASH,
    SPECIES_ROTOM_FROST,
    SPECIES_ROTOM_FAN,
    SPECIES_ROTOM_MOW,
};

static const uint16_t kFormsShaymin[] = {
    SPECIES_SHAYMIN_LAND,
    SPECIES_SHAYMIN_SKY,
};

static const uint16_t kFormsBasculin[] = {
    SPECIES_BASCULIN_RED_STRIPED,
    SPECIES_BASCULIN_BLUE_STRIPED,
    SPECIES_BASCULIN_WHITE_STRIPED,
};

static const uint16_t kFormsBasculegion[] = {
    SPECIES_BASCULEGION_M,
    SPECIES_BASCULEGION_F,
};

static const uint16_t kFormsDeerling[] = {
    SPECIES_DEERLING_SPRING,
    SPECIES_DEERLING_SUMMER,
    SPECIES_DEERLING_AUTUMN,
    SPECIES_DEERLING_WINTER,
};

static const uint16_t kFormsSawsbuck[] = {
    SPECIES_SAWSBUCK_SPRING,
    SPECIES_SAWSBUCK_SUMMER,
    SPECIES_SAWSBUCK_AUTUMN,
    SPECIES_SAWSBUCK_WINTER,
};

static const uint16_t kFormsTornadus[] = {
    SPECIES_TORNADUS_INCARNATE,
    SPECIES_TORNADUS_THERIAN,
};

static const uint16_t kFormsThundurus[] = {
    SPECIES_THUNDURUS_INCARNATE,
    SPECIES_THUNDURUS_THERIAN,
};

static const uint16_t kFormsLandorus[] = {
    SPECIES_LANDORUS_INCARNATE,
    SPECIES_LANDORUS_THERIAN,
};

static const uint16_t kFormsEnamorus[] = {
    SPECIES_ENAMORUS_INCARNATE,
    SPECIES_ENAMORUS_THERIAN,
};

static const uint16_t kFormsVivillion[] = {
    SPECIES_VIVILLON_MEADOW,
    SPECIES_VIVILLON_ARCHIPELAGO,
    SPECIES_VIVILLON_CONTINENTAL,
    SPECIES_VIVILLON_ELEGANT,
    SPECIES_VIVILLON_GARDEN,
    SPECIES_VIVILLON_HIGH_PLAINS,
    SPECIES_VIVILLON_ICY_SNOW,
    SPECIES_VIVILLON_JUNGLE,
    SPECIES_VIVILLON_MARINE,
    SPECIES_VIVILLON_MODERN,
    SPECIES_VIVILLON_MONSOON,
    SPECIES_VIVILLON_OCEAN,
    SPECIES_VIVILLON_POLAR,
    SPECIES_VIVILLON_RIVER,
    SPECIES_VIVILLON_SANDSTORM,
    SPECIES_VIVILLON_SAVANNA,
    SPECIES_VIVILLON_SUN,
    SPECIES_VIVILLON_TUNDRA,
    SPECIES_VIVILLON_POKEBALL,
    SPECIES_VIVILLON_FANCY,
};

static const std::uint16_t kFormsFlabebe[] = {
    SPECIES_FLABEBE_RED,
    SPECIES_FLABEBE_YELLOW,
    SPECIES_FLABEBE_ORANGE,
    SPECIES_FLABEBE_BLUE,
    SPECIES_FLABEBE_WHITE,
};

static const std::uint16_t kFormsFloette[] = {
    SPECIES_FLOETTE_RED,
    SPECIES_FLOETTE_YELLOW,
    SPECIES_FLOETTE_ORANGE,
    SPECIES_FLOETTE_BLUE,
    SPECIES_FLOETTE_WHITE,
};

static const std::uint16_t kFormsFlorges[] = {
    SPECIES_FLORGES_RED,
    SPECIES_FLORGES_YELLOW,
    SPECIES_FLORGES_ORANGE,
    SPECIES_FLORGES_BLUE,
    SPECIES_FLORGES_WHITE,
};

static const std::uint16_t kFormsFurfrou[] = {
    SPECIES_FURFROU_NATURAL,
    SPECIES_FURFROU_HEART_TRIM,
    SPECIES_FURFROU_DIAMOND_TRIM,
    SPECIES_FURFROU_STAR_TRIM,
    SPECIES_FURFROU_PHARAOH_TRIM,
    SPECIES_FURFROU_KABUKI_TRIM,
    SPECIES_FURFROU_LA_REINE_TRIM,
    SPECIES_FURFROU_MATRON_TRIM,
    SPECIES_FURFROU_DANDY_TRIM,
    SPECIES_FURFROU_DEBUTANTE_TRIM,
};

static const std::uint16_t kFormsMeowstic[] = {
    SPECIES_MEOWSTIC_M,
    SPECIES_MEOWSTIC_F,
};

static const std::uint16_t kFormsPumpkaboo[] = {
    SPECIES_PUMPKABOO_AVERAGE,
    SPECIES_PUMPKABOO_SMALL,
    SPECIES_PUMPKABOO_LARGE,
    SPECIES_PUMPKABOO_SUPER,
};

static const std::uint16_t kFormsGourgeist[] = {
    SPECIES_GOURGEIST_AVERAGE,
    SPECIES_GOURGEIST_SMALL,
    SPECIES_GOURGEIST_LARGE,
    SPECIES_GOURGEIST_SUPER,
};

/* We only use that Zygarde */
static const std::uint16_t kFormsZygarde[] = {
    SPECIES_ZYGARDE_10,
    SPECIES_ZYGARDE_50,
};

static const std::uint16_t kFormsHoopa[] = {
    SPECIES_HOOPA_CONFINED,
    SPECIES_HOOPA_UNBOUND,
};

static const std::uint16_t kFormsOricorio[] = {
    SPECIES_ORICORIO_BAILE,
    SPECIES_ORICORIO_POM_POM,
    SPECIES_ORICORIO_PAU,
    SPECIES_ORICORIO_SENSU,
};

static const std::uint16_t kFormsLycanroc[] = {
    SPECIES_LYCANROC_MIDDAY,
    SPECIES_LYCANROC_MIDNIGHT,
    SPECIES_LYCANROC_DUSK,
};

static const std::uint16_t kFormsMinior[] = {
    SPECIES_MINIOR_RED,
    SPECIES_MINIOR_ORANGE,
    SPECIES_MINIOR_YELLOW,
    SPECIES_MINIOR_GREEN,
    SPECIES_MINIOR_BLUE,
    SPECIES_MINIOR_INDIGO,
    SPECIES_MINIOR_VIOLET
};

static const std::uint16_t kFormsMagearna[] = {
    SPECIES_MAGEARNA,
    SPECIES_MAGEARNA_ORIGINAL,
};

static const std::uint16_t kFormsToxtricity[] = {
    SPECIES_TOXTRICITY_AMPED,
    SPECIES_TOXTRICITY_LOW_KEY,
};

static const std::uint16_t kFormsSinistea[] = {
    SPECIES_SINISTEA_PHONY,
    SPECIES_SINISTEA_ANTIQUE,
};

static const std::uint16_t kFormsPolteageist[] = {
    SPECIES_POLTEAGEIST_PHONY,
    SPECIES_POLTEAGEIST_ANTIQUE,
};

static const std::uint16_t kFormsAlcremie[] = {
    SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL,
    SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_BERRY_VANILLA_CREAM,
    SPECIES_ALCREMIE_BERRY_RUBY_CREAM,
    SPECIES_ALCREMIE_BERRY_MATCHA_CREAM,
    SPECIES_ALCREMIE_BERRY_MINT_CREAM,
    SPECIES_ALCREMIE_BERRY_LEMON_CREAM,
    SPECIES_ALCREMIE_BERRY_SALTED_CREAM,
    SPECIES_ALCREMIE_BERRY_RUBY_SWIRL,
    SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_LOVE_VANILLA_CREAM,
    SPECIES_ALCREMIE_LOVE_RUBY_CREAM,
    SPECIES_ALCREMIE_LOVE_MATCHA_CREAM,
    SPECIES_ALCREMIE_LOVE_MINT_CREAM,
    SPECIES_ALCREMIE_LOVE_LEMON_CREAM,
    SPECIES_ALCREMIE_LOVE_SALTED_CREAM,
    SPECIES_ALCREMIE_LOVE_RUBY_SWIRL,
    SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_STAR_VANILLA_CREAM,
    SPECIES_ALCREMIE_STAR_RUBY_CREAM,
    SPECIES_ALCREMIE_STAR_MATCHA_CREAM,
    SPECIES_ALCREMIE_STAR_MINT_CREAM,
    SPECIES_ALCREMIE_STAR_LEMON_CREAM,
    SPECIES_ALCREMIE_STAR_SALTED_CREAM,
    SPECIES_ALCREMIE_STAR_RUBY_SWIRL,
    SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM,
    SPECIES_ALCREMIE_CLOVER_RUBY_CREAM,
    SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM,
    SPECIES_ALCREMIE_CLOVER_MINT_CREAM,
    SPECIES_ALCREMIE_CLOVER_LEMON_CREAM,
    SPECIES_ALCREMIE_CLOVER_SALTED_CREAM,
    SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL,
    SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM,
    SPECIES_ALCREMIE_FLOWER_RUBY_CREAM,
    SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM,
    SPECIES_ALCREMIE_FLOWER_MINT_CREAM,
    SPECIES_ALCREMIE_FLOWER_LEMON_CREAM,
    SPECIES_ALCREMIE_FLOWER_SALTED_CREAM,
    SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL,
    SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM,
    SPECIES_ALCREMIE_RIBBON_RUBY_CREAM,
    SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM,
    SPECIES_ALCREMIE_RIBBON_MINT_CREAM,
    SPECIES_ALCREMIE_RIBBON_LEMON_CREAM,
    SPECIES_ALCREMIE_RIBBON_SALTED_CREAM,
    SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL,
    SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL,
};

static const std::uint16_t kFormsIndeedee[] = {
    SPECIES_INDEEDEE_M,
    SPECIES_INDEEDEE_F,
};

static const std::uint16_t kFormsUrshifu[] = {
    SPECIES_URSHIFU_SINGLE_STRIKE,
    SPECIES_URSHIFU_RAPID_STRIKE,
};

static const std::uint16_t kFormsZarude[] = {
    SPECIES_ZARUDE,
    SPECIES_ZARUDE_DADA,
};

static const std::uint16_t kFormsUrsaluna[] = {
    SPECIES_URSALUNA,
    SPECIES_URSALUNA_BLOODMOON,
};

static const std::uint16_t kFormsOinkologne[] = {
    SPECIES_OINKOLOGNE_M,
    SPECIES_OINKOLOGNE_F,
};

static const std::uint16_t kFormsMaushold[] = {
    SPECIES_MAUSHOLD_THREE,
    SPECIES_MAUSHOLD_FOUR,
};

static const std::uint16_t kFormsSquawkabily[] = {
    SPECIES_SQUAWKABILLY_GREEN,
    SPECIES_SQUAWKABILLY_BLUE,
    SPECIES_SQUAWKABILLY_YELLOW,
    SPECIES_SQUAWKABILLY_WHITE,
};

static const std::uint16_t kFormsTatsugiri[] = {
    SPECIES_TATSUGIRI_CURLY,
    SPECIES_TATSUGIRI_DROOPY,
    SPECIES_TATSUGIRI_STRETCHY,
};

static const std::uint16_t kFormsDudunspace[] = {
    SPECIES_DUDUNSPARCE_TWO_SEGMENT,
    SPECIES_DUDUNSPARCE_THREE_SEGMENT,
};

static const std::uint16_t kFormsGimmighoul[] = {
    SPECIES_GIMMIGHOUL_CHEST,
    SPECIES_GIMMIGHOUL_ROAMING,
};

static const std::uint16_t kFormsPoltchageist[] = {
    SPECIES_POLTCHAGEIST_COUNTERFEIT,
    SPECIES_POLTCHAGEIST_ARTISAN,
};

static const std::uint16_t kFormsSinistcha[] = {
    SPECIES_SINISTCHA_UNREMARKABLE,
    SPECIES_SINISTCHA_MASTERPIECE,
};

static const std::uint16_t kFormsRattata[] = {
    SPECIES_RATTATA,
    SPECIES_RATTATA_ALOLA,
};

static const std::uint16_t kFormsRaticate[] = {
    SPECIES_RATICATE,
    SPECIES_RATICATE_ALOLA,
};

static const std::uint16_t kFormsRaichu[] = {
    SPECIES_RAICHU,
    SPECIES_RAICHU_ALOLA,
};

static const std::uint16_t kFormsSandshrew[] = {
    SPECIES_SANDSHREW,
    SPECIES_SANDSHREW_ALOLA,
};

static const std::uint16_t kFormsSandslash[] = {
    SPECIES_SANDSLASH,
    SPECIES_SANDSLASH_ALOLA,
};

static const std::uint16_t kFormsVulpix[] = {
    SPECIES_VULPIX,
    SPECIES_VULPIX_ALOLA,
};

static const std::uint16_t kFormsNinetales[] = {
    SPECIES_NINETALES,
    SPECIES_NINETALES_ALOLA,
};

static const std::uint16_t kFormsDiglett[] = {
    SPECIES_DIGLETT,
    SPECIES_DIGLETT_ALOLA,
};

static const std::uint16_t kFormsDugtrio[] = {
    SPECIES_DUGTRIO,
    SPECIES_DUGTRIO_ALOLA,
};

static const std::uint16_t kFormsMeowth[] = {
    SPECIES_MEOWTH,
    SPECIES_MEOWTH_ALOLA,
    SPECIES_MEOWTH_GALAR,
};

static const std::uint16_t kFormsPersian[] = {
    SPECIES_PERSIAN,
    SPECIES_PERSIAN_ALOLA,
};

static const std::uint16_t kFormsGrowlithe[] = {
    SPECIES_GROWLITHE,
    SPECIES_GROWLITHE_HISUI,
};

static const std::uint16_t kFormsArcanine[] = {
    SPECIES_ARCANINE,
    SPECIES_ARCANINE_HISUI,
};

static const std::uint16_t kFormsGeodude[] = {
    SPECIES_GEODUDE,
    SPECIES_GEODUDE_ALOLA,
};

static const std::uint16_t kFormsGraveler[] = {
    SPECIES_GRAVELER,
    SPECIES_GRAVELER_ALOLA,
};

static const std::uint16_t kFormsGolem[] = {
    SPECIES_GOLEM,
    SPECIES_GOLEM_ALOLA,
};

static const std::uint16_t kFormsPonyta[] = {
    SPECIES_PONYTA,
    SPECIES_PONYTA_GALAR,
};

static const std::uint16_t kFormsRapidash[] = {
    SPECIES_RAPIDASH,
    SPECIES_RAPIDASH_GALAR,
};

static const std::uint16_t kFormsSlowpoke[] = {
    SPECIES_SLOWPOKE,
    SPECIES_SLOWPOKE_GALAR,
};

static const std::uint16_t kFormsSlowbro[] = {
    SPECIES_SLOWBRO,
    SPECIES_SLOWBRO_GALAR,
};

static const std::uint16_t kFormsfarfetchd[] = {
    SPECIES_FARFETCHD,
    SPECIES_FARFETCHD_GALAR,
};

static const std::uint16_t kFormsGrimer[] = {
    SPECIES_GRIMER,
    SPECIES_GRIMER_ALOLA,
};

static const std::uint16_t kFormsMuk[] = {
    SPECIES_MUK,
    SPECIES_MUK_ALOLA,
};

static const std::uint16_t kFormsVoltorb[] = {
    SPECIES_VOLTORB,
    SPECIES_VOLTORB_HISUI,
};

static const std::uint16_t kFormsElectrode[] = {
    SPECIES_ELECTRODE,
    SPECIES_ELECTRODE_HISUI,
};

static const std::uint16_t kFormsExeggutor[] = {
    SPECIES_EXEGGUTOR,
    SPECIES_EXEGGUTOR_ALOLA,
};

static const std::uint16_t kFormsMarowak[] = {
    SPECIES_MAROWAK,
    SPECIES_MAROWAK_ALOLA,
};

static const std::uint16_t kFormsWeezing[] = {
    SPECIES_WEEZING,
    SPECIES_WEEZING_GALAR,
};

static const std::uint16_t kFormsMrMime[] = {
    SPECIES_MR_MIME,
    SPECIES_MR_MIME_GALAR,
};

static const std::uint16_t kFormsArticuno[] = {
    SPECIES_ARTICUNO,
    SPECIES_ARTICUNO_GALAR,
};

static const std::uint16_t kFormsZapdos[] = {
    SPECIES_ZAPDOS,
    SPECIES_ZAPDOS_GALAR,
};

static const std::uint16_t kFormsMoltres[] = {
    SPECIES_MOLTRES,
    SPECIES_MOLTRES_GALAR,
};

static const std::uint16_t kFormsTyphlosion[] = {
    SPECIES_TYPHLOSION,
    SPECIES_TYPHLOSION_HISUI,
};

static const std::uint16_t kFormsWooper[] = {
    SPECIES_WOOPER,
    SPECIES_WOOPER_PALDEA,
};

static const std::uint16_t kFormsSlowking[] = {
    SPECIES_SLOWKING,
    SPECIES_SLOWKING_GALAR,
};

static const std::uint16_t kFormsQwilfish[] = {
    SPECIES_QWILFISH,
    SPECIES_QWILFISH_HISUI,
};

static const std::uint16_t kFormsSneasel[] = {
    SPECIES_SNEASEL,
    SPECIES_SNEASEL_HISUI,
};

static const std::uint16_t kFormsCorsola[] = {
    SPECIES_CORSOLA,
    SPECIES_CORSOLA_GALAR,
};

static const std::uint16_t kFormsZigzagoon[] = {
    SPECIES_ZIGZAGOON,
    SPECIES_ZIGZAGOON_GALAR,
};

static const std::uint16_t kFormsLinoone[] = {
    SPECIES_LINOONE,
    SPECIES_LINOONE_GALAR,
};

static const std::uint16_t kFormsSamurott[] = {
    SPECIES_SAMUROTT,
    SPECIES_SAMUROTT_HISUI,
};

static const std::uint16_t kFormsLiligant[] = {
    SPECIES_LILLIGANT,
    SPECIES_LILLIGANT_HISUI,
};

static const std::uint16_t kFormsDarumaka[] = {
    SPECIES_DARUMAKA,
    SPECIES_DARUMAKA_GALAR,
};

static const uint16_t kFormsDarmanitan[] = {
    SPECIES_DARMANITAN,
    SPECIES_DARMANITAN_GALAR,
};

static const std::uint16_t kFormsYamask[] = {
    SPECIES_YAMASK,
    SPECIES_YAMASK_GALAR,
};

static const std::uint16_t kFormsZorua[] = {
    SPECIES_ZORUA,
    SPECIES_ZORUA_HISUI,
};

static const std::uint16_t kFormsZoroark[] = {
    SPECIES_ZOROARK,
    SPECIES_ZOROARK_HISUI,
};

static const std::uint16_t kFormsStunfisk[] = {
    SPECIES_STUNFISK,
    SPECIES_STUNFISK_GALAR,
};

static const std::uint16_t kFormsBraviary[] = {
    SPECIES_BRAVIARY,
    SPECIES_BRAVIARY_HISUI,
};

static const std::uint16_t kFormsSliggoo[] = {
    SPECIES_SLIGGOO,
    SPECIES_SLIGGOO_HISUI,
};

static const std::uint16_t kFormsGoodra[] = {
    SPECIES_GOODRA,
    SPECIES_GOODRA_HISUI,
};

static const std::uint16_t kFormsAvalugg[] = {
    SPECIES_AVALUGG,
    SPECIES_AVALUGG_HISUI,
};

static const std::uint16_t kFormsDecidueye[] = {
    SPECIES_DECIDUEYE,
    SPECIES_DECIDUEYE_HISUI,
};

static const std::uint16_t kLegendaries[] =
{
    SPECIES_ZAPDOS,
    SPECIES_ZAPDOS_GALAR,
    SPECIES_MOLTRES,
    SPECIES_MOLTRES_GALAR,
    SPECIES_ARTICUNO,
    SPECIES_ARTICUNO_GALAR,
    SPECIES_MEWTWO,
    SPECIES_MEW,
    SPECIES_RAIKOU,
    SPECIES_ENTEI,
    SPECIES_SUICUNE,
    SPECIES_LUGIA,
    SPECIES_HO_OH,
    SPECIES_CELEBI,
    SPECIES_REGIROCK,
    SPECIES_REGICE,
    SPECIES_REGISTEEL,
    SPECIES_LATIAS,
    SPECIES_LATIOS,
    SPECIES_KYOGRE,
    SPECIES_GROUDON,
    SPECIES_RAYQUAZA,
    SPECIES_JIRACHI,
    SPECIES_DEOXYS_NORMAL,
    SPECIES_DEOXYS_ATTACK,
    SPECIES_DEOXYS_DEFENSE,
    SPECIES_DEOXYS_SPEED,
    SPECIES_UXIE,
    SPECIES_MESPRIT,
    SPECIES_AZELF,
    SPECIES_DIALGA,
    SPECIES_PALKIA,
    SPECIES_HEATRAN,
    SPECIES_REGIGIGAS,
    SPECIES_GIRATINA,
    SPECIES_CRESSELIA,
    SPECIES_PHIONE,
    SPECIES_MANAPHY,
    SPECIES_DARKRAI,
    SPECIES_SHAYMIN_LAND,
    SPECIES_SHAYMIN_SKY,
    SPECIES_ARCEUS,
    SPECIES_VICTINI,
    SPECIES_COBALION,
    SPECIES_TERRAKION,
    SPECIES_VIRIZION,
    SPECIES_TORNADUS_INCARNATE,
    SPECIES_TORNADUS_THERIAN,
    SPECIES_THUNDURUS_INCARNATE,
    SPECIES_THUNDURUS_THERIAN,
    SPECIES_LANDORUS_INCARNATE,
    SPECIES_LANDORUS_THERIAN,
    SPECIES_RESHIRAM,
    SPECIES_ZEKROM,
    SPECIES_KYUREM,
    SPECIES_KELDEO,
    SPECIES_MELOETTA,
    SPECIES_GENESECT,
    SPECIES_XERNEAS,
    SPECIES_YVELTAL,
    SPECIES_ZYGARDE_10,
    SPECIES_ZYGARDE_50,
    SPECIES_DIANCIE,
    SPECIES_HOOPA_CONFINED,
    SPECIES_HOOPA_UNBOUND,
    SPECIES_VOLCANION,
    SPECIES_TYPE_NULL,
    SPECIES_SILVALLY,
    SPECIES_TAPU_KOKO,
    SPECIES_TAPU_LELE,
    SPECIES_TAPU_BULU,
    SPECIES_TAPU_FINI,
    SPECIES_COSMOG,
    SPECIES_COSMOEM,
    SPECIES_SOLGALEO,
    SPECIES_LUNALA,
    SPECIES_NECROZMA,
    SPECIES_MAGEARNA,
    SPECIES_MAGEARNA_ORIGINAL,
    SPECIES_MARSHADOW,
    SPECIES_ZERAORA,
    SPECIES_MELTAN,
    SPECIES_MELMETAL,
    SPECIES_ZACIAN,
    SPECIES_ZAMAZENTA,
    SPECIES_ETERNATUS,
    SPECIES_KUBFU,
    SPECIES_URSHIFU_SINGLE_STRIKE,
    SPECIES_URSHIFU_RAPID_STRIKE,
    SPECIES_REGIELEKI,
    SPECIES_REGIDRAGO,
    SPECIES_GLASTRIER,
    SPECIES_SPECTRIER,
    SPECIES_CALYREX,
    SPECIES_ENAMORUS_INCARNATE,
    SPECIES_ENAMORUS_THERIAN,
    SPECIES_ZARUDE,
    SPECIES_ZARUDE_DADA,
    SPECIES_WO_CHIEN,
    SPECIES_CHIEN_PAO,
    SPECIES_TING_LU,
    SPECIES_CHI_YU,
    SPECIES_KORAIDON,
    SPECIES_MIRAIDON,
    SPECIES_OKIDOGI,
    SPECIES_MUNKIDORI,
    SPECIES_FEZANDIPITI,
    SPECIES_OGERPON,
    SPECIES_TERAPAGOS,
    SPECIES_PECHARUNT,
};

std::uint16_t Pokemon::randPokemon(Random& rng)
{
    std::uint16_t value;

    value = randInt(rng, 1025) + 1;
    switch (value)
    {
    case SPECIES_TAUROS: if (randInt(rng, 2) == 0) return SAMPLE(rng, kFormsTaurosPaldea); break;
    case SPECIES_UNOWN: return SAMPLE(rng, kFormsUnown);
    case SPECIES_DEOXYS: return SAMPLE(rng, kFormsDeoxys);
    case SPECIES_BURMY: return SAMPLE(rng, kFormsBurmy);
    case SPECIES_WORMADAM: return SAMPLE(rng, kFormsWormadam);
    case SPECIES_SHELLOS: return SAMPLE(rng, kFormsShellos);
    case SPECIES_GASTRODON: return SAMPLE(rng, kFormsGastrodon);
    case SPECIES_ROTOM: return SAMPLE(rng, kFormsRotom);
    case SPECIES_SHAYMIN: return SAMPLE(rng, kFormsShaymin);
    case SPECIES_BASCULIN: return SAMPLE(rng, kFormsBasculin);
    case SPECIES_BASCULEGION: return SAMPLE(rng, kFormsBasculegion);
    case SPECIES_DEERLING: return SAMPLE(rng, kFormsDeerling);
    case SPECIES_SAWSBUCK: return SAMPLE(rng, kFormsSawsbuck);
    case SPECIES_TORNADUS: return SAMPLE(rng, kFormsTornadus);
    case SPECIES_THUNDURUS: return SAMPLE(rng, kFormsThundurus);
    case SPECIES_LANDORUS: return SAMPLE(rng, kFormsLandorus);
    case SPECIES_ENAMORUS: return SAMPLE(rng, kFormsEnamorus);
    case SPECIES_VIVILLON: return SAMPLE(rng, kFormsVivillion);
    case SPECIES_FLABEBE: return SAMPLE(rng, kFormsFlabebe);
    case SPECIES_FLOETTE: return SAMPLE(rng, kFormsFloette);
    case SPECIES_FLORGES: return SAMPLE(rng, kFormsFlorges);
    case SPECIES_FURFROU: return SAMPLE(rng, kFormsFurfrou);
    case SPECIES_MEOWSTIC: return SAMPLE(rng, kFormsMeowstic);
    case SPECIES_PUMPKABOO: return SAMPLE(rng, kFormsPumpkaboo);
    case SPECIES_GOURGEIST: return SAMPLE(rng, kFormsGourgeist);
    case SPECIES_ZYGARDE: return SAMPLE(rng, kFormsZygarde);
    case SPECIES_HOOPA: return SAMPLE(rng, kFormsHoopa);
    case SPECIES_ORICORIO: return SAMPLE(rng, kFormsOricorio);
    case SPECIES_LYCANROC: return SAMPLE(rng, kFormsLycanroc);
    case SPECIES_MINIOR: return SAMPLE(rng, kFormsMinior);
    case SPECIES_MAGEARNA: return SAMPLE(rng, kFormsMagearna);
    case SPECIES_TOXTRICITY: return SAMPLE(rng, kFormsToxtricity);
    case SPECIES_SINISTEA: return SAMPLE(rng, kFormsSinistea);
    case SPECIES_POLTEAGEIST: return SAMPLE(rng, kFormsPolteageist);
    case SPECIES_ALCREMIE: return SAMPLE(rng, kFormsAlcremie);
    case SPECIES_INDEEDEE: return SAMPLE(rng, kFormsIndeedee);
    case SPECIES_URSHIFU: return SAMPLE(rng, kFormsUrshifu);
    case SPECIES_ZARUDE: return SAMPLE(rng, kFormsZarude);
    case SPECIES_URSALUNA: return SAMPLE(rng, kFormsUrsaluna);
    case SPECIES_OINKOLOGNE: return SAMPLE(rng, kFormsOinkologne);
    case SPECIES_MAUSHOLD: return SAMPLE(rng, kFormsMaushold);
    case SPECIES_SQUAWKABILLY: return SAMPLE(rng, kFormsSquawkabily);
    case SPECIES_TATSUGIRI: return SAMPLE(rng, kFormsTatsugiri);
    case SPECIES_DUDUNSPARCE: return SAMPLE(rng, kFormsDudunspace);
    case SPECIES_GIMMIGHOUL: return SAMPLE(rng, kFormsGimmighoul);
    case SPECIES_POLTCHAGEIST: return SAMPLE(rng, kFormsPoltchageist);
    case SPECIES_SINISTCHA: return SAMPLE(rng, kFormsSinistcha);
    case SPECIES_RATTATA: return SAMPLE(rng, kFormsRattata);
    case SPECIES_RATICATE: return SAMPLE(rng, kFormsRaticate);
    case SPECIES_RAICHU: return SAMPLE(rng, kFormsRaichu);
    case SPECIES_SANDSHREW: return SAMPLE(rng, kFormsSandshrew);
    case SPECIES_SANDSLASH: return SAMPLE(rng, kFormsSandslash);
    case SPECIES_VULPIX: return SAMPLE(rng, kFormsVulpix);
    case SPECIES_NINETALES: return SAMPLE(rng, kFormsNinetales);
    case SPECIES_DIGLETT: return SAMPLE(rng, kFormsDiglett);
    case SPECIES_DUGTRIO: return SAMPLE(rng, kFormsDugtrio);
    case SPECIES_MEOWTH: return SAMPLE(rng, kFormsMeowth);
    case SPECIES_PERSIAN: return SAMPLE(rng, kFormsPersian);
    case SPECIES_GROWLITHE: return SAMPLE(rng, kFormsGrowlithe);
    case SPECIES_ARCANINE: return SAMPLE(rng, kFormsArcanine);
    case SPECIES_GEODUDE: return SAMPLE(rng, kFormsGeodude);
    case SPECIES_GRAVELER: return SAMPLE(rng, kFormsGraveler);
    case SPECIES_GOLEM: return SAMPLE(rng, kFormsGolem);
    case SPECIES_PONYTA: return SAMPLE(rng, kFormsPonyta);
    case SPECIES_RAPIDASH: return SAMPLE(rng, kFormsRapidash);
    case SPECIES_SLOWPOKE: return SAMPLE(rng, kFormsSlowpoke);
    case SPECIES_SLOWBRO: return SAMPLE(rng, kFormsSlowbro);
    case SPECIES_FARFETCHD: return SAMPLE(rng, kFormsfarfetchd);
    case SPECIES_GRIMER: return SAMPLE(rng, kFormsGrimer);
    case SPECIES_MUK: return SAMPLE(rng, kFormsMuk);
    case SPECIES_VOLTORB: return SAMPLE(rng, kFormsVoltorb);
    case SPECIES_ELECTRODE: return SAMPLE(rng, kFormsElectrode);
    case SPECIES_EXEGGUTOR: return SAMPLE(rng, kFormsExeggutor);
    case SPECIES_MAROWAK: return SAMPLE(rng, kFormsMarowak);
    case SPECIES_WEEZING: return SAMPLE(rng, kFormsWeezing);
    case SPECIES_MR_MIME: return SAMPLE(rng, kFormsMrMime);
    case SPECIES_ARTICUNO: return SAMPLE(rng, kFormsArticuno);
    case SPECIES_ZAPDOS: return SAMPLE(rng, kFormsZapdos);
    case SPECIES_MOLTRES: return SAMPLE(rng, kFormsMoltres);
    case SPECIES_TYPHLOSION: return SAMPLE(rng, kFormsTyphlosion);
    case SPECIES_WOOPER: return SAMPLE(rng, kFormsWooper);
    case SPECIES_SLOWKING: return SAMPLE(rng, kFormsSlowking);
    case SPECIES_QWILFISH: return SAMPLE(rng, kFormsQwilfish);
    case SPECIES_SNEASEL: return SAMPLE(rng, kFormsSneasel);
    case SPECIES_CORSOLA: return SAMPLE(rng, kFormsCorsola);
    case SPECIES_ZIGZAGOON: return SAMPLE(rng, kFormsZigzagoon);
    case SPECIES_LINOONE: return SAMPLE(rng, kFormsLinoone);
    case SPECIES_SAMUROTT: return SAMPLE(rng, kFormsSamurott);
    case SPECIES_LILLIGANT: return SAMPLE(rng, kFormsLiligant);
    case SPECIES_DARUMAKA: return SAMPLE(rng, kFormsDarumaka);
    case SPECIES_DARMANITAN: return SAMPLE(rng, kFormsDarmanitan);
    case SPECIES_YAMASK: return SAMPLE(rng, kFormsYamask);
    case SPECIES_ZORUA: return SAMPLE(rng, kFormsZorua);
    case SPECIES_ZOROARK: return SAMPLE(rng, kFormsZoroark);
    case SPECIES_STUNFISK: return SAMPLE(rng, kFormsStunfisk);
    case SPECIES_BRAVIARY: return SAMPLE(rng, kFormsBraviary);
    case SPECIES_SLIGGOO: return SAMPLE(rng, kFormsSliggoo);
    case SPECIES_GOODRA: return SAMPLE(rng, kFormsGoodra);
    case SPECIES_AVALUGG: return SAMPLE(rng, kFormsAvalugg);
    case SPECIES_DECIDUEYE: return SAMPLE(rng, kFormsDecidueye);
    }

    return value;
}

bool Pokemon::isValidOutOfBattle(std::uint16_t id)
{
    if (id == 0)
        return false;

    if (id <= 1025)
        return true;

    switch (id)
    {
    case SPECIES_TAUROS_PALDEA_COMBAT:
    case SPECIES_TAUROS_PALDEA_BLAZE:
    case SPECIES_TAUROS_PALDEA_AQUA:
    case SPECIES_UNOWN_A:
    case SPECIES_UNOWN_B:
    case SPECIES_UNOWN_C:
    case SPECIES_UNOWN_D:
    case SPECIES_UNOWN_E:
    case SPECIES_UNOWN_F:
    case SPECIES_UNOWN_G:
    case SPECIES_UNOWN_H:
    case SPECIES_UNOWN_I:
    case SPECIES_UNOWN_J:
    case SPECIES_UNOWN_K:
    case SPECIES_UNOWN_L:
    case SPECIES_UNOWN_M:
    case SPECIES_UNOWN_N:
    case SPECIES_UNOWN_O:
    case SPECIES_UNOWN_P:
    case SPECIES_UNOWN_Q:
    case SPECIES_UNOWN_R:
    case SPECIES_UNOWN_S:
    case SPECIES_UNOWN_T:
    case SPECIES_UNOWN_U:
    case SPECIES_UNOWN_V:
    case SPECIES_UNOWN_W:
    case SPECIES_UNOWN_X:
    case SPECIES_UNOWN_Y:
    case SPECIES_UNOWN_Z:
    case SPECIES_UNOWN_EXCLAMATION:
    case SPECIES_UNOWN_QUESTION:
    case SPECIES_DEOXYS_NORMAL:
    case SPECIES_DEOXYS_ATTACK:
    case SPECIES_DEOXYS_DEFENSE:
    case SPECIES_DEOXYS_SPEED:
    case SPECIES_BURMY_PLANT:
    case SPECIES_BURMY_SANDY:
    case SPECIES_BURMY_TRASH:
    case SPECIES_WORMADAM_PLANT:
    case SPECIES_WORMADAM_SANDY:
    case SPECIES_WORMADAM_TRASH:
    case SPECIES_SHELLOS_WEST:
    case SPECIES_SHELLOS_EAST:
    case SPECIES_GASTRODON_WEST:
    case SPECIES_GASTRODON_EAST:
    case SPECIES_ROTOM:
    case SPECIES_ROTOM_HEAT:
    case SPECIES_ROTOM_WASH:
    case SPECIES_ROTOM_FROST:
    case SPECIES_ROTOM_FAN:
    case SPECIES_ROTOM_MOW:
    case SPECIES_SHAYMIN_LAND:
    case SPECIES_SHAYMIN_SKY:
    case SPECIES_BASCULIN_RED_STRIPED:
    case SPECIES_BASCULIN_BLUE_STRIPED:
    case SPECIES_BASCULIN_WHITE_STRIPED:
    case SPECIES_BASCULEGION_M:
    case SPECIES_BASCULEGION_F:
    case SPECIES_DEERLING_SPRING:
    case SPECIES_DEERLING_SUMMER:
    case SPECIES_DEERLING_AUTUMN:
    case SPECIES_DEERLING_WINTER:
    case SPECIES_SAWSBUCK_SPRING:
    case SPECIES_SAWSBUCK_SUMMER:
    case SPECIES_SAWSBUCK_AUTUMN:
    case SPECIES_SAWSBUCK_WINTER:
    case SPECIES_TORNADUS_INCARNATE:
    case SPECIES_TORNADUS_THERIAN:
    case SPECIES_THUNDURUS_INCARNATE:
    case SPECIES_THUNDURUS_THERIAN:
    case SPECIES_LANDORUS_INCARNATE:
    case SPECIES_LANDORUS_THERIAN:
    case SPECIES_ENAMORUS_INCARNATE:
    case SPECIES_ENAMORUS_THERIAN:
    case SPECIES_VIVILLON_MEADOW:
    case SPECIES_VIVILLON_ARCHIPELAGO:
    case SPECIES_VIVILLON_CONTINENTAL:
    case SPECIES_VIVILLON_ELEGANT:
    case SPECIES_VIVILLON_GARDEN:
    case SPECIES_VIVILLON_HIGH_PLAINS:
    case SPECIES_VIVILLON_ICY_SNOW:
    case SPECIES_VIVILLON_JUNGLE:
    case SPECIES_VIVILLON_MARINE:
    case SPECIES_VIVILLON_MODERN:
    case SPECIES_VIVILLON_MONSOON:
    case SPECIES_VIVILLON_OCEAN:
    case SPECIES_VIVILLON_POLAR:
    case SPECIES_VIVILLON_RIVER:
    case SPECIES_VIVILLON_SANDSTORM:
    case SPECIES_VIVILLON_SAVANNA:
    case SPECIES_VIVILLON_SUN:
    case SPECIES_VIVILLON_TUNDRA:
    case SPECIES_VIVILLON_POKEBALL:
    case SPECIES_VIVILLON_FANCY:
    case SPECIES_FLABEBE_RED:
    case SPECIES_FLABEBE_YELLOW:
    case SPECIES_FLABEBE_ORANGE:
    case SPECIES_FLABEBE_BLUE:
    case SPECIES_FLABEBE_WHITE:
    case SPECIES_FLOETTE_RED:
    case SPECIES_FLOETTE_YELLOW:
    case SPECIES_FLOETTE_ORANGE:
    case SPECIES_FLOETTE_BLUE:
    case SPECIES_FLOETTE_WHITE:
    case SPECIES_FLORGES_RED:
    case SPECIES_FLORGES_YELLOW:
    case SPECIES_FLORGES_ORANGE:
    case SPECIES_FLORGES_BLUE:
    case SPECIES_FLORGES_WHITE:
    case SPECIES_FURFROU_NATURAL:
    case SPECIES_FURFROU_HEART_TRIM:
    case SPECIES_FURFROU_DIAMOND_TRIM:
    case SPECIES_FURFROU_STAR_TRIM:
    case SPECIES_FURFROU_PHARAOH_TRIM:
    case SPECIES_FURFROU_KABUKI_TRIM:
    case SPECIES_FURFROU_LA_REINE_TRIM:
    case SPECIES_FURFROU_MATRON_TRIM:
    case SPECIES_FURFROU_DANDY_TRIM:
    case SPECIES_FURFROU_DEBUTANTE_TRIM:
    case SPECIES_MEOWSTIC_M:
    case SPECIES_MEOWSTIC_F:
    case SPECIES_PUMPKABOO_AVERAGE:
    case SPECIES_PUMPKABOO_SMALL:
    case SPECIES_PUMPKABOO_LARGE:
    case SPECIES_PUMPKABOO_SUPER:
    case SPECIES_GOURGEIST_AVERAGE:
    case SPECIES_GOURGEIST_SMALL:
    case SPECIES_GOURGEIST_LARGE:
    case SPECIES_GOURGEIST_SUPER:
    case SPECIES_ZYGARDE_10:
    case SPECIES_ZYGARDE_50:
    case SPECIES_HOOPA_CONFINED:
    case SPECIES_HOOPA_UNBOUND:
    case SPECIES_ORICORIO_BAILE:
    case SPECIES_ORICORIO_POM_POM:
    case SPECIES_ORICORIO_PAU:
    case SPECIES_ORICORIO_SENSU:
    case SPECIES_LYCANROC_MIDDAY:
    case SPECIES_LYCANROC_MIDNIGHT:
    case SPECIES_LYCANROC_DUSK:
    case SPECIES_MINIOR_RED:
    case SPECIES_MINIOR_ORANGE:
    case SPECIES_MINIOR_YELLOW:
    case SPECIES_MINIOR_GREEN:
    case SPECIES_MINIOR_BLUE:
    case SPECIES_MINIOR_INDIGO:
    case SPECIES_MINIOR_VIOLET:
    case SPECIES_MAGEARNA:
    case SPECIES_MAGEARNA_ORIGINAL:
    case SPECIES_TOXTRICITY_AMPED:
    case SPECIES_TOXTRICITY_LOW_KEY:
    case SPECIES_SINISTEA_PHONY:
    case SPECIES_SINISTEA_ANTIQUE:
    case SPECIES_POLTEAGEIST_PHONY:
    case SPECIES_POLTEAGEIST_ANTIQUE:
    case SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM:
    case SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM:
    case SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM:
    case SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM:
    case SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM:
    case SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM:
    case SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL:
    case SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL:
    case SPECIES_ALCREMIE_BERRY_VANILLA_CREAM:
    case SPECIES_ALCREMIE_BERRY_RUBY_CREAM:
    case SPECIES_ALCREMIE_BERRY_MATCHA_CREAM:
    case SPECIES_ALCREMIE_BERRY_MINT_CREAM:
    case SPECIES_ALCREMIE_BERRY_LEMON_CREAM:
    case SPECIES_ALCREMIE_BERRY_SALTED_CREAM:
    case SPECIES_ALCREMIE_BERRY_RUBY_SWIRL:
    case SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL:
    case SPECIES_ALCREMIE_LOVE_VANILLA_CREAM:
    case SPECIES_ALCREMIE_LOVE_RUBY_CREAM:
    case SPECIES_ALCREMIE_LOVE_MATCHA_CREAM:
    case SPECIES_ALCREMIE_LOVE_MINT_CREAM:
    case SPECIES_ALCREMIE_LOVE_LEMON_CREAM:
    case SPECIES_ALCREMIE_LOVE_SALTED_CREAM:
    case SPECIES_ALCREMIE_LOVE_RUBY_SWIRL:
    case SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL:
    case SPECIES_ALCREMIE_STAR_VANILLA_CREAM:
    case SPECIES_ALCREMIE_STAR_RUBY_CREAM:
    case SPECIES_ALCREMIE_STAR_MATCHA_CREAM:
    case SPECIES_ALCREMIE_STAR_MINT_CREAM:
    case SPECIES_ALCREMIE_STAR_LEMON_CREAM:
    case SPECIES_ALCREMIE_STAR_SALTED_CREAM:
    case SPECIES_ALCREMIE_STAR_RUBY_SWIRL:
    case SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL:
    case SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM:
    case SPECIES_ALCREMIE_CLOVER_RUBY_CREAM:
    case SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM:
    case SPECIES_ALCREMIE_CLOVER_MINT_CREAM:
    case SPECIES_ALCREMIE_CLOVER_LEMON_CREAM:
    case SPECIES_ALCREMIE_CLOVER_SALTED_CREAM:
    case SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL:
    case SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL:
    case SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM:
    case SPECIES_ALCREMIE_FLOWER_RUBY_CREAM:
    case SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM:
    case SPECIES_ALCREMIE_FLOWER_MINT_CREAM:
    case SPECIES_ALCREMIE_FLOWER_LEMON_CREAM:
    case SPECIES_ALCREMIE_FLOWER_SALTED_CREAM:
    case SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL:
    case SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL:
    case SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM:
    case SPECIES_ALCREMIE_RIBBON_RUBY_CREAM:
    case SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM:
    case SPECIES_ALCREMIE_RIBBON_MINT_CREAM:
    case SPECIES_ALCREMIE_RIBBON_LEMON_CREAM:
    case SPECIES_ALCREMIE_RIBBON_SALTED_CREAM:
    case SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL:
    case SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL:
    case SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL:
    case SPECIES_INDEEDEE_M:
    case SPECIES_INDEEDEE_F:
    case SPECIES_URSHIFU_SINGLE_STRIKE:
    case SPECIES_URSHIFU_RAPID_STRIKE:
    case SPECIES_ZARUDE:
    case SPECIES_ZARUDE_DADA:
    case SPECIES_URSALUNA:
    case SPECIES_URSALUNA_BLOODMOON:
    case SPECIES_OINKOLOGNE_M:
    case SPECIES_OINKOLOGNE_F:
    case SPECIES_MAUSHOLD_THREE:
    case SPECIES_MAUSHOLD_FOUR:
    case SPECIES_SQUAWKABILLY_GREEN:
    case SPECIES_SQUAWKABILLY_BLUE:
    case SPECIES_SQUAWKABILLY_YELLOW:
    case SPECIES_SQUAWKABILLY_WHITE:
    case SPECIES_TATSUGIRI_CURLY:
    case SPECIES_TATSUGIRI_DROOPY:
    case SPECIES_TATSUGIRI_STRETCHY:
    case SPECIES_DUDUNSPARCE_TWO_SEGMENT:
    case SPECIES_DUDUNSPARCE_THREE_SEGMENT:
    case SPECIES_GIMMIGHOUL_CHEST:
    case SPECIES_GIMMIGHOUL_ROAMING:
    case SPECIES_POLTCHAGEIST_COUNTERFEIT:
    case SPECIES_POLTCHAGEIST_ARTISAN:
    case SPECIES_SINISTCHA_UNREMARKABLE:
    case SPECIES_SINISTCHA_MASTERPIECE:
    case SPECIES_RATTATA:
    case SPECIES_RATTATA_ALOLA:
    case SPECIES_RATICATE:
    case SPECIES_RATICATE_ALOLA:
    case SPECIES_RAICHU:
    case SPECIES_RAICHU_ALOLA:
    case SPECIES_SANDSHREW:
    case SPECIES_SANDSHREW_ALOLA:
    case SPECIES_SANDSLASH:
    case SPECIES_SANDSLASH_ALOLA:
    case SPECIES_VULPIX:
    case SPECIES_VULPIX_ALOLA:
    case SPECIES_NINETALES:
    case SPECIES_NINETALES_ALOLA:
    case SPECIES_DIGLETT:
    case SPECIES_DIGLETT_ALOLA:
    case SPECIES_DUGTRIO:
    case SPECIES_DUGTRIO_ALOLA:
    case SPECIES_MEOWTH:
    case SPECIES_MEOWTH_ALOLA:
    case SPECIES_MEOWTH_GALAR:
    case SPECIES_PERSIAN:
    case SPECIES_PERSIAN_ALOLA:
    case SPECIES_GROWLITHE:
    case SPECIES_GROWLITHE_HISUI:
    case SPECIES_ARCANINE:
    case SPECIES_ARCANINE_HISUI:
    case SPECIES_GEODUDE:
    case SPECIES_GEODUDE_ALOLA:
    case SPECIES_GRAVELER:
    case SPECIES_GRAVELER_ALOLA:
    case SPECIES_GOLEM:
    case SPECIES_GOLEM_ALOLA:
    case SPECIES_PONYTA:
    case SPECIES_PONYTA_GALAR:
    case SPECIES_RAPIDASH:
    case SPECIES_RAPIDASH_GALAR:
    case SPECIES_SLOWPOKE:
    case SPECIES_SLOWPOKE_GALAR:
    case SPECIES_SLOWBRO:
    case SPECIES_SLOWBRO_GALAR:
    case SPECIES_FARFETCHD:
    case SPECIES_FARFETCHD_GALAR:
    case SPECIES_GRIMER:
    case SPECIES_GRIMER_ALOLA:
    case SPECIES_MUK:
    case SPECIES_MUK_ALOLA:
    case SPECIES_VOLTORB:
    case SPECIES_VOLTORB_HISUI:
    case SPECIES_ELECTRODE:
    case SPECIES_ELECTRODE_HISUI:
    case SPECIES_EXEGGUTOR:
    case SPECIES_EXEGGUTOR_ALOLA:
    case SPECIES_MAROWAK:
    case SPECIES_MAROWAK_ALOLA:
    case SPECIES_WEEZING:
    case SPECIES_WEEZING_GALAR:
    case SPECIES_MR_MIME:
    case SPECIES_MR_MIME_GALAR:
    case SPECIES_ARTICUNO:
    case SPECIES_ARTICUNO_GALAR:
    case SPECIES_ZAPDOS:
    case SPECIES_ZAPDOS_GALAR:
    case SPECIES_MOLTRES:
    case SPECIES_MOLTRES_GALAR:
    case SPECIES_TYPHLOSION:
    case SPECIES_TYPHLOSION_HISUI:
    case SPECIES_WOOPER:
    case SPECIES_WOOPER_PALDEA:
    case SPECIES_SLOWKING:
    case SPECIES_SLOWKING_GALAR:
    case SPECIES_QWILFISH:
    case SPECIES_QWILFISH_HISUI:
    case SPECIES_SNEASEL:
    case SPECIES_SNEASEL_HISUI:
    case SPECIES_CORSOLA:
    case SPECIES_CORSOLA_GALAR:
    case SPECIES_ZIGZAGOON:
    case SPECIES_ZIGZAGOON_GALAR:
    case SPECIES_LINOONE:
    case SPECIES_LINOONE_GALAR:
    case SPECIES_SAMUROTT:
    case SPECIES_SAMUROTT_HISUI:
    case SPECIES_LILLIGANT:
    case SPECIES_LILLIGANT_HISUI:
    case SPECIES_DARUMAKA:
    case SPECIES_DARUMAKA_GALAR:
    case SPECIES_DARMANITAN:
    case SPECIES_DARMANITAN_GALAR:
    case SPECIES_YAMASK:
    case SPECIES_YAMASK_GALAR:
    case SPECIES_ZORUA:
    case SPECIES_ZORUA_HISUI:
    case SPECIES_ZOROARK:
    case SPECIES_ZOROARK_HISUI:
    case SPECIES_STUNFISK:
    case SPECIES_STUNFISK_GALAR:
    case SPECIES_BRAVIARY:
    case SPECIES_BRAVIARY_HISUI:
    case SPECIES_SLIGGOO:
    case SPECIES_SLIGGOO_HISUI:
    case SPECIES_GOODRA:
    case SPECIES_GOODRA_HISUI:
    case SPECIES_AVALUGG:
    case SPECIES_AVALUGG_HISUI:
    case SPECIES_DECIDUEYE:
    case SPECIES_DECIDUEYE_HISUI:
        return true;
    }

    return false;
}

bool Pokemon::isLegendary(std::uint16_t pokemon)
{
    for (unsigned i = 0; i < ARRAY_SIZE(kLegendaries); i++)
    {
        if (pokemon == kLegendaries[i])
            return true;
    }

    return false;
}

uint16_t Pokemon::randMove(Random& rng)
{
    uint16_t move;
    bool valid;

    for (;;)
    {
        move = randInt(rng, MOVES_COUNT);

        valid = true;
        if (IS_Z_MOVE(move) || IS_MAX_MOVE(move))
            valid = false;
        else
        {
            switch (move)
            {
            /* Invalid moves */
            case MOVE_NONE:
            case MOVE_STRUGGLE:
            case MOVE_BLAZING_TORQUE:
            case MOVE_WICKED_TORQUE:
            case MOVE_NOXIOUS_TORQUE:
            case MOVE_COMBAT_TORQUE:
            case MOVE_MAGICAL_TORQUE:
                valid = false;
                break;
            }
        }

        if (valid)
            return move;
    }
}

std::uint16_t Pokemon::evolution(const Database& db, Random& rand, std::uint16_t speciesId, int depth)
{
    int index;

    while (depth--)
    {
        auto evoCount = db.pokemons.evolutionsCounts[speciesId];
        if (evoCount == 0)
            return speciesId;
        if (evoCount == 1)
        {
            index = 0;
        }
        else
        {
            index = rand.next() % evoCount;
        }

        const auto& dbEntry = db.pokemons.evolutions[speciesId];
        speciesId = dbEntry[index];
    }

    return speciesId;
}

std::uint16_t Pokemon::randItemTmHm(Random& rng)
{
    return ITEM_TM01 + (rng.next() % 108);
}

std::uint16_t Pokemon::randItemGeneric(Random& rng)
{
    return kItems[randInt(rng, ARRAY_SIZE(kItems))];
}
