#include <shuffler/SpeciesGroups.h>
#include <emerald/include/constants/species.h>

const uint16_t SpeciesGroups::Unown[] = {
    SPECIES_UNOWN_A, SPECIES_UNOWN_B, SPECIES_UNOWN_C, SPECIES_UNOWN_D, SPECIES_UNOWN_E,
    SPECIES_UNOWN_F, SPECIES_UNOWN_G, SPECIES_UNOWN_H, SPECIES_UNOWN_I, SPECIES_UNOWN_J,
    SPECIES_UNOWN_K, SPECIES_UNOWN_L, SPECIES_UNOWN_M, SPECIES_UNOWN_N, SPECIES_UNOWN_O,
    SPECIES_UNOWN_P, SPECIES_UNOWN_Q, SPECIES_UNOWN_R, SPECIES_UNOWN_S, SPECIES_UNOWN_T,
    SPECIES_UNOWN_U, SPECIES_UNOWN_V, SPECIES_UNOWN_W, SPECIES_UNOWN_X, SPECIES_UNOWN_Y,
    SPECIES_UNOWN_Z, SPECIES_UNOWN_EMARK, SPECIES_UNOWN_QMARK,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Castform[] = {
    SPECIES_CASTFORM, SPECIES_CASTFORM_SUNNY, SPECIES_CASTFORM_RAINY, SPECIES_CASTFORM_SNOWY,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Deoxys[] = {
    SPECIES_DEOXYS, SPECIES_DEOXYS_ATTACK, SPECIES_DEOXYS_DEFENSE, SPECIES_DEOXYS_SPEED,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Burmy[] = {
    SPECIES_BURMY_PLANT_CLOAK, SPECIES_BURMY_SANDY_CLOAK, SPECIES_BURMY_TRASH_CLOAK,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Wormadam[] = {
    SPECIES_WORMADAM_PLANT_CLOAK, SPECIES_WORMADAM_SANDY_CLOAK, SPECIES_WORMADAM_TRASH_CLOAK,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Cherrim[] = {
    SPECIES_CHERRIM_OVERCAST, SPECIES_CHERRIM_SUNSHINE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Shellos[] = {
    SPECIES_SHELLOS_WEST_SEA, SPECIES_SHELLOS_EAST_SEA,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Gastrodon[] = {
    SPECIES_GASTRODON_WEST_SEA, SPECIES_GASTRODON_EAST_SEA,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Rotom[] = {
    SPECIES_ROTOM, SPECIES_ROTOM_HEAT, SPECIES_ROTOM_WASH, SPECIES_ROTOM_FROST, SPECIES_ROTOM_FAN, SPECIES_ROTOM_MOW,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Dialga[] = {
    SPECIES_DIALGA, SPECIES_DIALGA_ORIGIN,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Palkia[] = {
    SPECIES_PALKIA, SPECIES_PALKIA_ORIGIN,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Arceus[] = {
    SPECIES_ARCEUS_NORMAL, SPECIES_ARCEUS_FIRE, SPECIES_ARCEUS_WATER, SPECIES_ARCEUS_ELECTRIC, SPECIES_ARCEUS_GRASS,
    SPECIES_ARCEUS_ICE, SPECIES_ARCEUS_FIGHTING, SPECIES_ARCEUS_POISON, SPECIES_ARCEUS_GROUND, SPECIES_ARCEUS_FLYING,
    SPECIES_ARCEUS_PSYCHIC, SPECIES_ARCEUS_BUG, SPECIES_ARCEUS_ROCK, SPECIES_ARCEUS_GHOST, SPECIES_ARCEUS_DRAGON,
    SPECIES_ARCEUS_DARK, SPECIES_ARCEUS_STEEL, SPECIES_ARCEUS_FAIRY,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Basculegion[] = {
    SPECIES_BASCULEGION_MALE, SPECIES_BASCULEGION_FEMALE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::DarmanitanNormal[] = {
    SPECIES_DARMANITAN_STANDARD_MODE, SPECIES_DARMANITAN_ZEN_MODE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::DarmanitanGalarian[] = {
    SPECIES_DARMANITAN_GALARIAN_STANDARD_MODE, SPECIES_DARMANITAN_GALARIAN_ZEN_MODE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Deerling[] = {
    SPECIES_DEERLING_SPRING, SPECIES_DEERLING_SUMMER, SPECIES_DEERLING_AUTUMN, SPECIES_DEERLING_WINTER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Sawsbuck[] = {
    SPECIES_SAWSBUCK_SPRING, SPECIES_SAWSBUCK_SUMMER, SPECIES_SAWSBUCK_AUTUMN, SPECIES_SAWSBUCK_WINTER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Keldeo[] = {
    SPECIES_KELDEO_ORDINARY, SPECIES_KELDEO_RESOLUTE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Meloetta[] = {
    SPECIES_MELOETTA_ARIA, SPECIES_MELOETTA_PIROUETTE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Genesect[] = {
    SPECIES_GENESECT, SPECIES_GENESECT_BURN_DRIVE, SPECIES_GENESECT_CHILL_DRIVE, SPECIES_GENESECT_DOUSE_DRIVE, SPECIES_GENESECT_SHOCK_DRIVE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Greninja[] = {
    SPECIES_GRENINJA, SPECIES_GRENINJA_ASH,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Vivillon[] = {
    SPECIES_VIVILLON_ICY_SNOW,
    SPECIES_VIVILLON_POLAR,
    SPECIES_VIVILLON_TUNDRA,
    SPECIES_VIVILLON_CONTINENTAL,
    SPECIES_VIVILLON_GARDEN,
    SPECIES_VIVILLON_ELEGANT,
    SPECIES_VIVILLON_MEADOW,
    SPECIES_VIVILLON_MODERN,
    SPECIES_VIVILLON_MARINE,
    SPECIES_VIVILLON_ARCHIPELAGO,
    SPECIES_VIVILLON_HIGH_PLAINS,
    SPECIES_VIVILLON_SANDSTORM,
    SPECIES_VIVILLON_RIVER,
    SPECIES_VIVILLON_MONSOON,
    SPECIES_VIVILLON_SAVANNA,
    SPECIES_VIVILLON_SUN,
    SPECIES_VIVILLON_OCEAN,
    SPECIES_VIVILLON_JUNGLE,
    SPECIES_VIVILLON_FANCY,
    SPECIES_VIVILLON_POKE_BALL,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Flabebe[] = {
    SPECIES_FLABEBE_RED_FLOWER, SPECIES_FLABEBE_YELLOW_FLOWER, SPECIES_FLABEBE_ORANGE_FLOWER, SPECIES_FLABEBE_BLUE_FLOWER, SPECIES_FLABEBE_WHITE_FLOWER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Floette[] = {
    SPECIES_FLOETTE_RED_FLOWER, SPECIES_FLOETTE_YELLOW_FLOWER, SPECIES_FLOETTE_ORANGE_FLOWER, SPECIES_FLOETTE_BLUE_FLOWER, SPECIES_FLOETTE_WHITE_FLOWER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Florges[] = {
    SPECIES_FLORGES_RED_FLOWER, SPECIES_FLORGES_YELLOW_FLOWER, SPECIES_FLORGES_ORANGE_FLOWER, SPECIES_FLORGES_BLUE_FLOWER, SPECIES_FLORGES_WHITE_FLOWER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Furfrou[] = {
    SPECIES_FURFROU, SPECIES_FURFROU_HEART_TRIM, SPECIES_FURFROU_DIAMOND_TRIM, SPECIES_FURFROU_STAR_TRIM, SPECIES_FURFROU_PHARAOH_TRIM,
    SPECIES_FURFROU_KABUKI_TRIM, SPECIES_FURFROU_LA_REINE_TRIM, SPECIES_FURFROU_MATRON_TRIM, SPECIES_FURFROU_DANDY_TRIM, SPECIES_FURFROU_DEBUTANTE_TRIM,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Aegislash[] = {
    SPECIES_AEGISLASH_SHIELD, SPECIES_AEGISLASH_BLADE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Pumpkaboo[] = {
    SPECIES_PUMPKABOO_AVERAGE, SPECIES_PUMPKABOO_SMALL, SPECIES_PUMPKABOO_LARGE, SPECIES_PUMPKABOO_SUPER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Gourgeist[] = {
    SPECIES_GOURGEIST_AVERAGE, SPECIES_GOURGEIST_SMALL, SPECIES_GOURGEIST_LARGE, SPECIES_GOURGEIST_SUPER,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Xerneas[] = {
    SPECIES_XERNEAS_NEUTRAL, SPECIES_XERNEAS_ACTIVE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Zygarde[] = {
    SPECIES_ZYGARDE_50, SPECIES_ZYGARDE_10, SPECIES_ZYGARDE_COMPLETE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Hoopa[] = {
    SPECIES_HOOPA, SPECIES_HOOPA_UNBOUND,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Oricorio[] = {
    SPECIES_ORICORIO_BAILE, SPECIES_ORICORIO_POM_POM, SPECIES_ORICORIO_PAU, SPECIES_ORICORIO_SENSU,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Wishiwashi[] = {
    SPECIES_WISHIWASHI_SOLO, SPECIES_WISHIWASHI_SCHOOL,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Silvally[] = {
    SPECIES_SILVALLY, SPECIES_SILVALLY_FIGHTING, SPECIES_SILVALLY_FLYING, SPECIES_SILVALLY_POISON, SPECIES_SILVALLY_GROUND,
    SPECIES_SILVALLY_ROCK, SPECIES_SILVALLY_BUG, SPECIES_SILVALLY_GHOST, SPECIES_SILVALLY_STEEL, SPECIES_SILVALLY_FIRE,
    SPECIES_SILVALLY_WATER, SPECIES_SILVALLY_GRASS, SPECIES_SILVALLY_ELECTRIC, SPECIES_SILVALLY_PSYCHIC, SPECIES_SILVALLY_ICE,
    SPECIES_SILVALLY_DRAGON, SPECIES_SILVALLY_DARK, SPECIES_SILVALLY_FAIRY,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Minior[] = {
    SPECIES_MINIOR_CORE_RED, SPECIES_MINIOR_CORE_BLUE, SPECIES_MINIOR_CORE_ORANGE,
    SPECIES_MINIOR_CORE_YELLOW, SPECIES_MINIOR_CORE_INDIGO, SPECIES_MINIOR_CORE_GREEN, SPECIES_MINIOR_CORE_VIOLET,
    SPECIES_MINIOR_METEOR_RED, SPECIES_MINIOR_METEOR_BLUE, SPECIES_MINIOR_METEOR_ORANGE,
    SPECIES_MINIOR_METEOR_YELLOW, SPECIES_MINIOR_METEOR_INDIGO, SPECIES_MINIOR_METEOR_GREEN, SPECIES_MINIOR_METEOR_VIOLET,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Mimikyu[] = {
    SPECIES_MIMIKYU, SPECIES_MIMIKYU_BUSTED,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Magearna[] = {
    SPECIES_MAGEARNA, SPECIES_MAGEARNA_ORIGINAL_COLOR,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Cramorant[] = {
    SPECIES_CRAMORANT, SPECIES_CRAMORANT_GULPING, SPECIES_CRAMORANT_GORGING,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Sinistea[] = {
    SPECIES_SINISTEA_PHONY, SPECIES_SINISTEA_ANTIQUE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Polteageist[] = {
    SPECIES_POLTEAGEIST_PHONY, SPECIES_POLTEAGEIST_ANTIQUE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Alcremie[] = {
    SPECIES_ALCREMIE_STRAWBERRY_VANILLA_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_RUBY_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_MATCHA_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_MINT_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_LEMON_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_SALTED_CREAM,
    SPECIES_ALCREMIE_STRAWBERRY_RUBY_SWIRL,
    SPECIES_ALCREMIE_STRAWBERRY_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_STRAWBERRY_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_BERRY_VANILLA_CREAM,
    SPECIES_ALCREMIE_BERRY_RUBY_CREAM,
    SPECIES_ALCREMIE_BERRY_MATCHA_CREAM,
    SPECIES_ALCREMIE_BERRY_MINT_CREAM,
    SPECIES_ALCREMIE_BERRY_LEMON_CREAM,
    SPECIES_ALCREMIE_BERRY_SALTED_CREAM,
    SPECIES_ALCREMIE_BERRY_RUBY_SWIRL,
    SPECIES_ALCREMIE_BERRY_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_BERRY_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_LOVE_VANILLA_CREAM,
    SPECIES_ALCREMIE_LOVE_RUBY_CREAM,
    SPECIES_ALCREMIE_LOVE_MATCHA_CREAM,
    SPECIES_ALCREMIE_LOVE_MINT_CREAM,
    SPECIES_ALCREMIE_LOVE_LEMON_CREAM,
    SPECIES_ALCREMIE_LOVE_SALTED_CREAM,
    SPECIES_ALCREMIE_LOVE_RUBY_SWIRL,
    SPECIES_ALCREMIE_LOVE_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_LOVE_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_STAR_VANILLA_CREAM,
    SPECIES_ALCREMIE_STAR_RUBY_CREAM,
    SPECIES_ALCREMIE_STAR_MATCHA_CREAM,
    SPECIES_ALCREMIE_STAR_MINT_CREAM,
    SPECIES_ALCREMIE_STAR_LEMON_CREAM,
    SPECIES_ALCREMIE_STAR_SALTED_CREAM,
    SPECIES_ALCREMIE_STAR_RUBY_SWIRL,
    SPECIES_ALCREMIE_STAR_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_STAR_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_CLOVER_VANILLA_CREAM,
    SPECIES_ALCREMIE_CLOVER_RUBY_CREAM,
    SPECIES_ALCREMIE_CLOVER_MATCHA_CREAM,
    SPECIES_ALCREMIE_CLOVER_MINT_CREAM,
    SPECIES_ALCREMIE_CLOVER_LEMON_CREAM,
    SPECIES_ALCREMIE_CLOVER_SALTED_CREAM,
    SPECIES_ALCREMIE_CLOVER_RUBY_SWIRL,
    SPECIES_ALCREMIE_CLOVER_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_CLOVER_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_FLOWER_VANILLA_CREAM,
    SPECIES_ALCREMIE_FLOWER_RUBY_CREAM,
    SPECIES_ALCREMIE_FLOWER_MATCHA_CREAM,
    SPECIES_ALCREMIE_FLOWER_MINT_CREAM,
    SPECIES_ALCREMIE_FLOWER_LEMON_CREAM,
    SPECIES_ALCREMIE_FLOWER_SALTED_CREAM,
    SPECIES_ALCREMIE_FLOWER_RUBY_SWIRL,
    SPECIES_ALCREMIE_FLOWER_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_FLOWER_RAINBOW_SWIRL,
    SPECIES_ALCREMIE_RIBBON_VANILLA_CREAM,
    SPECIES_ALCREMIE_RIBBON_RUBY_CREAM,
    SPECIES_ALCREMIE_RIBBON_MATCHA_CREAM,
    SPECIES_ALCREMIE_RIBBON_MINT_CREAM,
    SPECIES_ALCREMIE_RIBBON_LEMON_CREAM,
    SPECIES_ALCREMIE_RIBBON_SALTED_CREAM,
    SPECIES_ALCREMIE_RIBBON_RUBY_SWIRL,
    SPECIES_ALCREMIE_RIBBON_CARAMEL_SWIRL,
    SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL,
    SPECIES_NONE,
};

const uint16_t SpeciesGroups::Eiscue[] = {
    SPECIES_EISCUE_ICE_FACE, SPECIES_EISCUE_NOICE_FACE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Morpeko[] = {
    SPECIES_MORPEKO, SPECIES_MORPEKO_HANGRY,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Zacian[] = {
    SPECIES_ZACIAN_HERO_OF_MANY_BATTLES, SPECIES_ZACIAN_CROWNED_SWORD,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Zamazenta[] = {
    SPECIES_ZAMAZENTA_HERO_OF_MANY_BATTLES, SPECIES_ZAMAZENTA_CROWNED_SHIELD,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Urshifru[] = {
    SPECIES_URSHIFU_SINGLE_STRIKE_STYLE, SPECIES_URSHIFU_RAPID_STRIKE_STYLE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Zarude[] = {
    SPECIES_ZARUDE, SPECIES_ZARUDE_DADA,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Maushold[] = {
    SPECIES_MAUSHOLD_FAMILY_OF_THREE, SPECIES_MAUSHOLD_FAMILY_OF_FOUR,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Squawkabilly[] = {
    SPECIES_SQUAWKABILLY_GREEN_PLUMAGE, SPECIES_SQUAWKABILLY_BLUE_PLUMAGE, SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE, SPECIES_SQUAWKABILLY_WHITE_PLUMAGE,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Palafin[] = {
    SPECIES_PALAFIN_ZERO, SPECIES_PALAFIN_HERO,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Tatsugiri[] = {
    SPECIES_TATSUGIRI_CURLY, SPECIES_TATSUGIRI_DROOPY, SPECIES_TATSUGIRI_STRETCHY,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Dudunsparce[] = {
    SPECIES_DUDUNSPARCE_TWO_SEGMENT, SPECIES_DUDUNSPARCE_THREE_SEGMENT,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Poltchageist[] = {
    SPECIES_POLTCHAGEIST_COUNTERFEIT, SPECIES_POLTCHAGEIST_ARTISAN,
    SPECIES_NONE
};

const uint16_t SpeciesGroups::Sinistcha[] = {
    SPECIES_SINISTCHA_UNREMARKABLE, SPECIES_SINISTCHA_MASTERPIECE,
    SPECIES_NONE
};
